### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MaxMatti** [veloren/veloren#109]
While this message was displayed, Veloren was still running and playable. Clicking ok caused it to exit.

![grafik](https://github.com/veloren/veloren/assets/1584478/41289685-6721-4adc-a357-aaca2e03266a)

**Comment by MaxMatti** [comment]
The log file mentioned in the error message:
[2023-08-06_voxygen.log](https://github.com/veloren/veloren/files/12269735/2023-08-06_voxygen.log)

**Comment by zesterer** [comment]
Hi,

We use GitLab for development, this repository is just a mirror. You can submit an issue [there](https://gitlab.com/veloren/veloren/-/issues/new).
