### ISSUE TITLE
important thingy

### ISSUE THREAD

**Issue by JasonTable** [veloren/veloren#110]
you might want to stop hotlinking images from discrod as they will be making a change that will break it. 

learn more here.

https://www.youtube.com/watch?v=rZ73h1qWb3c

also i know this is just a mirror but i dont use gitlab because its worse than github IMO. i dont like needing to complete 2 different CAPTCHAs to do anything.

just figured id let ya know. :-)

**Comment by zesterer** [comment]
Thanks for letting us know. We are aware and are already working on migrating away (we've known for a long while that using Discord as a CDN is sketchy and at best a temporary solution). I'm going to close this issue now since we don't actively use GH for tracking such issues.
