### ISSUE TITLE
Airship's collision model and pathfinder is kind of glitchy

### ISSUE THREAD

**Issue by cookiengineer** [veloren/veloren#116]
Hey there,

I was playing a little today, and in Amrenandam there's a bunch of Airships constantly colliding with things that are in their way. This also ironically leads to a heavy drain on CPU performance, as I'm guessing the collisions are constantly triggered while the entity tries to move.

Here's a couple of screenshots demonstrating the problem:

![airships](https://github.com/veloren/veloren/assets/592637/4550aff8-6396-4642-a21b-be59302390f5)
![airships2](https://github.com/veloren/veloren/assets/592637/96547782-4ec8-4cca-899d-7d6306be25c6)
![airships3](https://github.com/veloren/veloren/assets/592637/7eb92c32-e8b9-4c2e-b8a4-7339511154da)

**Comment by zesterer** [comment]
This is a known issue and is unfortunately very difficult to solve in one go. Incremental improvements to airship movement, pathfinding, and collisions are ongoing.
