### ISSUE TITLE
BUG black screen when cloud setting > minimal

### ISSUE THREAD

**Issue by Kowai** [veloren/veloren#74]
As mentionned in the discord chat today :

Mac os : Catalina 10.15.7

Terminal msg when changing to unsupported cloud setting : [INFO] [Veloren] Nov 07 22:42:29.524  WARN gfx_device_gl::shade: 	Log: WARNING: Could not find fragment shader output 'Target2' to match FragDataBinding request.

Black screen description :

Happening from the character selection window to the ingame.
Everything is black as if it was night but it isn't. bag items maps windows or chat show normally.

The texture and environement is showing normally when changing the cloud setting to "low" or "none".

**Comment by zesterer** [comment]
(Closing in favour of the GitLab issue, here: https://gitlab.com/veloren/veloren/-/issues/830)
