### ISSUE TITLE
Veloren load failure

### ISSUE THREAD

**Issue by mlohdael** [veloren/veloren#78]
[voxygen.log.2021-03-30.txt](https://github.com/veloren/veloren/files/6232124/voxygen.log.2021-03-30.txt)

> This error showed up while attempting to play on a Raspberry Pi 4B 4gb using Flatpak to install it.

**Comment by zesterer** [comment]
Hey, we've moved to GitLab.

As an aside, the Raspberry Pi only supports OpenGL 3.1, while Veloren needs 3.3 (hence the `OpenGlVersionNotSupported` error).
