### ISSUE TITLE
Manually select nvidia gpu

### ISSUE THREAD

**Issue by IJustDev** [veloren/veloren#79]
Hey there,

thanks for this project. I would really like to play it and further develop it but I am using Arch Linux with an Intel and Nvidia gpu. I would like to manually select which gpu should be used.

Thanks for any kind of help.
*IJustDev*

**Comment by IJustDev** [comment]
Ups will be moved to Gitlab.

**Comment by AngelOnFira** [comment]
Closing as it's on Gitlab :)
