### ISSUE TITLE
Veloren doesn`t start

### ISSUE THREAD

**Issue by RUMO-Barsoom** [veloren/veloren#85]
Hello,
my son has an older PC with Windows10. Installation is working fine and the airshipper is starting.
But then he always get a error-message.

His PC:
![System PC](https://user-images.githubusercontent.com/82439689/156417662-500256ec-bd6a-4f1c-9ddc-b0d3a672e74f.jpg)

The error message:
![error message](https://user-images.githubusercontent.com/82439689/156417914-440fd176-e25a-494f-8344-6b10a9119cb3.jpg)

Unfortunately, we can't see what exactly the problem is.

We tried the compatibility mode and also started it with admin privileges.
Are there any other options or is it something that the awesome Veloren team can fix?

Best thankful regards
Rumo

**Comment by zesterer** [comment]
Have you tried switching graphics backends in Airshipper?

Fwiw, the main project is hosted on GitLab, [here](https://gitlab.com/veloren/veloren/).

**Comment by RUMO-Barsoom** [comment]
How can I change, if I can`t start the game?
I only hear the music, the window open and then error message comes.

Ah ok. I thought Gitlab is even worse than Github, which in turn is worse than Codeberg.org.

**Comment by zesterer** [comment]
You can change the graphics backend the game uses by clicking the little cog icon in Airshipper. No need to open the game itself.

**Comment by AngelOnFira** [comment]
Since this is our mirror repo, I'm going to close the issue here. Feel free to re-open it on our [main repo on Gitlab](https://gitlab.com/veloren/veloren/) :)
