### ISSUE TITLE
can you make this game playable on the website, I will be very grateful if you make it a website version

### ISSUE THREAD

**Issue by ME1SEGAWON** [veloren/veloren#96]

**Comment by zesterer** [comment]
This repository is a mirror, we use [GitLab](https://gitlab.com/veloren/veloren/) for tracking issues.

There is a small possibility of a WASM port of Veloren in the future (which would allow the game to run in a web browser), but it's not a priority for us right now and probably won't be for the foreseeable future.

**Comment by ME1SEGAWON** [comment]
I really want to make an RPG game that can be played on the website, I will host it myself
